export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const SORT_INGREDIENTS: "SORT_INGREDIENTS" = "SORT_INGREDIENTS";
export const GET_INGREDIENTS_DATA: "GET_INGREDIENTS_DATA" =
  "GET_INGREDIENTS_DATA";
export const GET_INGREDIENTS_DATA_FAILED: "GET_INGREDIENTS_DATA_FAILED" =
  "GET_INGREDIENTS_DATA_FAILED";
export const GET_INGREDIENTS_DATA_SUCCESS: "GET_INGREDIENTS_DATA_SUCCESS" =
  "GET_INGREDIENTS_DATA_SUCCESS";

export const GET_ORDER_NUMBER: "GET_ORDER_NUMBER" = "GET_ORDER_NUMBER";
export const GET_ORDER_NUMBER_SUCCESS: "GET_ORDER_NUMBER_SUCCESS" =
  "GET_ORDER_NUMBER_SUCCESS";
export const GET_ORDER_NUMBER_FAILED: "GET_ORDER_NUMBER_FAILED" =
  "GET_ORDER_NUMBER_FAILED";

export const SEND_REGISTER: "SEND_REGISTER" = "SEND_REGISTER";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILED: "REGISTER_FAILED" = "REGISTER_FAILED";
export const SEND_LOGIN: "SEND_LOGIN" = "SEND_LOGIN";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILED: "LOGIN_FAILED" = "LOGIN_FAILED";
export const SEND_LOGOUT: "SEND_LOGOUT" = "SEND_LOGOUT";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED: "LOGOUT_FAILED" = "LOGOUT_FAILED";
export const GET_USER_DATA: "GET_USER_DATA" = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS" =
  "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILED: "GET_USER_DATA_FAILED" =
  "GET_USER_DATA_FAILED";
export const SEND_NEW_PROFILE_INFO: "SEND_NEW_PROFILE_INFO" =
  "SEND_NEW_PROFILE_INFO";
export const PROFILE_INFO_CHANGED_SUCCESS: "PROFILE_INFO_CHANGED_SUCCESS" =
  "PROFILE_INFO_CHANGED_SUCCESS";
export const PROFILE_INFO_CHANGED_FAILED: "PROFILE_INFO_CHANGED_FAILED" =
  "PROFILE_INFO_CHANGED_FAILED";
export const SEND_EMAIL: "SEND_EMAIL" = "SEND_EMAIL";
export const SEND_EMAIL_SUCCESS: "SEND_EMAIL_SUCCESS" = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILED: "SEND_EMAIL_FAILED" = "SEND_EMAIL_FAILED";
export const SEND_RESET_PASSWORD: "SEND_RESET_PASSWORD" = "SEND_RESET_PASSWORD";
export const SEND_RESET_PASSWORD_SUCCESS: "SEND_RESET_PASSWORD_SUCCESS" =
  "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAILED: "SEND_RESET_PASSWORD_FAILED" =
  "SEND_RESET_PASSWORD_FAILED";
